name: CI/CD Docker + Helm Multi-Cluster

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bitcoin-app

   

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./bitcoin-app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  
      - name: Install Helm
        uses: azure/setup-helm@v4

    
      - name: Configure kubeconfig (Cluster 1)
        run: |
          echo "${{ secrets.KUBECONFIG1 }}" | base64 -d > kubeconfig1
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig1

      - name: list the file directory 
        run: |
          pwd 
           ls -la 

      - name: Deploy to Kind Cluster 1 using Helm
        working-directory: ./helm
        run: |
          cd $GITHUB_WORKSPACE
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig1
          helm upgrade --install bitcoin-app ./helm/bitcoin-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}

   
      - name: Configure kubeconfig (Cluster 2)
        run: |
          echo "${{ secrets.KUBECONFIG2 }}" | base64 -d > kubeconfig2
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig2

      - name: Deploy to Kind Cluster 2 using Helm
        working-directory: ./helm
        run: |
          cd $GITHUB_WORKSPACE
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig2
          helm upgrade --install bitcoin-app ./helm/bitcoin-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}

  deploy-canary:
      runs-on: self-hosted
      needs: build-and-deploy
      steps:
        - uses: actions/checkout@v4

        - name: Configure kubeconfig (Cluster 2)
          run: |
            echo "${{ secrets.KUBECONFIG2 }}" | base64 -d > kubeconfig2
            export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig2

        - name: Deploy canary to cluster1
          working-directory: ./helm
          run: |
            cd $GITHUB_WORKSPACE
            export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig2
            helm upgrade --install bitcoin-app ./helm/bitcoin-app \
              --set image.tag=latest \
              --set replicaCount=1   

        - name: Monitor canary
          run: kubectl --kubeconfig=$GITHUB_WORKSPACE/kubeconfig2 rollout status deployment/bitcoin-app

  deploy-full:
      runs-on: self-hosted
      needs: [build-and-deploy, deploy-canary]
      steps:
        - uses: actions/checkout@v4
        - name: Configure kubeconfig (Cluster 1)
          run: |
            echo "${{ secrets.KUBECONFIG1 }}" | base64 -d > kubeconfig1
            export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig1
        - name: Deploy full version to cluster1
          run: |
            cd $GITHUB_WORKSPACE
              export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig1
              helm upgrade --install bitcoin-app ./helm/bitcoin-app \
                --set image.tag=latest \
                --set replicaCount=3  

        - name: Deploy new version to cluster2 (Blue-Green)
          run: |
            cd $GITHUB_WORKSPACE
            export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig2
            helm upgrade --install bitcoin-app ./helm/bitcoin-app \
              --set image.tag=latest

        - name: Monitor canary
          run: |
            kubectl --kubeconfig=$GITHUB_WORKSPACE/kubeconfig2 rollout status deployment/bitcoin-app
            kubectl --kubeconfig=$GITHUB_WORKSPACE/kubeconfig2 rollout history deployment/bitcoin-app