name: CI/CD Docker + Helm Multi-Cluster

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: bitcoin-app

   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        working-directory: ./bitcoin-app
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker Image
        working-directory: ./bitcoin-app
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  
      - name: Install Helm
        uses: azure/setup-helm@v4

    
      - name: Configure kubeconfig (Cluster 1)
        run: |
          echo "${{ secrets.KUBECONFIG1 }}" | base64 -d > kubeconfig1
          export KUBECONFIG=$PWD/kubeconfig1

      - name: Deploy to Kind Cluster 1 using Helm
        working-directory: ./helm
        run: |
          helm upgrade --install bitcoin-app helm/bitcoin-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}

   
      - name: Configure kubeconfig (Cluster 2)
        run: |
          echo "${{ secrets.KUBECONFIG2 }}" | base64 -d > kubeconfig2
          export KUBECONFIG=$PWD/kubeconfig2

      - name: Deploy to Kind Cluster 2 using Helm
        working-directory: ./helm
        run: |
          helm upgrade --install bitcoin-app helm/bitcoin-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}
